"""init_tables

Revision ID: c140727a1257
Revises: 
Create Date: 2025-12-14 21:29:33.054749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c140727a1257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='URL-friendly identifier (e.g. test-corp)'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.String(length=100), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("plan_type IN ('free', 'pro', 'enterprise')", name='ck_companies_plan_type'),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'", name='ck_companies_slug_format'),
    sa.PrimaryKeyConstraint('id', name='pk_companies_id'),
    sa.UniqueConstraint('email', name='uq_companies_email')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Company (workspace) this record belongs to'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_password_reset_tokens_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_company_id'), 'password_reset_tokens', ['company_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='employee', nullable=False, comment='User role (admin, hr, employee) - indexed for fast role-based access control queries'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Company (workspace) this record belongs to'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_users_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_email')
    )
    op.create_index('ix_company_email', 'users', ['company_id', 'email'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('employees',
    sa.Column('user_id', sa.Uuid(), nullable=True, comment="Optional user account ID. NULL means employee exists but doesn't have login credentials yet. When downgrading migrations that require NOT NULL, these records must be handled/deleted."),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False, comment='Job role/title'),
    sa.Column('joining_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='Optional employee ID/code - unique per company'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Company (workspace) this record belongs to'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_employees_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_employees_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_id', name='uq_employees_company_employee_id'),
    sa.UniqueConstraint('user_id', name='uq_employees_user_id')
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_role'), 'employees', ['role'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('name', sa.String(length=200), nullable=False, comment="Asset/item name (e.g., 'MacBook Pro 16')"),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='Type of asset (laptop, monitor, etc.)'),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='Serial number - unique within company'),
    sa.Column('status', sa.String(length=50), server_default='available', nullable=False, comment='Current status of the asset'),
    sa.Column('condition', sa.String(length=50), server_default='excellent', nullable=False, comment='Physical condition of the asset'),
    sa.Column('assigned_to', sa.Uuid(), nullable=True, comment='Employee currently assigned this asset. NULL if unassigned.'),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True, comment='Date when asset was issued/assigned to current employee'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Company (workspace) this record belongs to'),
    sa.CheckConstraint("condition IN ('excellent', 'good', 'fair', 'poor')", name='ck_assets_condition'),
    sa.CheckConstraint("status IN ('available', 'assigned', 'maintenance', 'retired')", name='ck_assets_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], name='fk_assets_employee', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_assets_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'serial_number', name='uq_assets_company_serial')
    )
    op.create_index(op.f('ix_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_assets_company_id'), 'assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('expenses',
    sa.Column('employee_id', sa.Uuid(), nullable=False, comment='Employee who submitted this expense'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Expense title/description'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Expense amount (e.g., 125.50)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the expense'),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False, comment='Date when the expense was incurred'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Current status of the expense reimbursement'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='URL/path to uploaded receipt file (optional)'),
    sa.Column('approved_by', sa.Uuid(), nullable=True, comment='User (HR/Admin) who approved/rejected this expense'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Date when expense was approved/rejected'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Reason for rejection (if status is rejected)'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Company (workspace) this record belongs to'),
    sa.CheckConstraint("(status = 'rejected' AND rejection_reason IS NOT NULL) OR (status != 'rejected')", name='ck_expenses_rejection_integrity'),
    sa.CheckConstraint("(status IN ('approved', 'reimbursed') AND approved_by IS NOT NULL AND approved_at IS NOT NULL) OR (status NOT IN ('approved', 'reimbursed'))", name='ck_expenses_approval_integrity'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'reimbursed')", name='ck_expenses_status'),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='fk_expenses_approved_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_expenses_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_expenses_employee', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_approved_by'), 'expenses', ['approved_by'], unique=False)
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_title'), 'expenses', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_title'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_approved_by'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_company_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_assigned_to'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_role'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index('ix_company_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_company_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

