"""add_slug_to_companies

Revision ID: 27686bb983bd
Revises: c6249ba0db35
Create Date: 2025-12-07 21:00:56.450361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27686bb983bd'
down_revision: Union[str, None] = 'c6249ba0db35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this asset belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.add_column('companies', sa.Column('slug', sa.String(length=50), server_default='temp-slug', nullable=False, comment='URL-friendly identifier (e.g. test-corp)'))
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Primary key - explicitly named as pk_companies_id',
               existing_nullable=False)
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Optional employee ID/code - unique per company',
               existing_comment='Optional employee ID/code',
               existing_nullable=True)
    op.alter_column('employees', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this employee belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_unique_constraint('uq_employees_company_employee_id', 'employees', ['company_id', 'employee_id'])
    op.alter_column('expenses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('expenses', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this expense belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_approved_by'), 'expenses', ['approved_by'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_comment='User role (admin, hr, employee) - indexed for fast role-based access control queries',
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('ix_company_email', 'users', ['company_id', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_email', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_comment='User role (admin, hr, employee) - indexed for fast role-based access control queries',
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
    op.drop_index(op.f('ix_expenses_approved_by'), table_name='expenses')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.alter_column('expenses', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this expense belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.alter_column('expenses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_employees_company_employee_id', 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this employee belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.alter_column('employees', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Optional employee ID/code',
               existing_comment='Optional employee ID/code - unique per company',
               existing_nullable=True)
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Primary key - explicitly named as pk_companies_id',
               existing_nullable=False)
    op.drop_column('companies', 'slug')
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this asset belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###

