"""id

Revision ID: 55c626fc25c6
Revises: c6249ba0db35
Create Date: 2025-12-07 12:32:39.143877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c626fc25c6'
down_revision: Union[str, None] = 'c6249ba0db35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (tenant) this asset belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment=None,
               existing_comment='Primary key - explicitly named as pk_companies_id',
               existing_nullable=False)
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.alter_column('employees', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (tenant) this employee belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.alter_column('expenses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('expenses', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (tenant) this expense belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.alter_column('expenses', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this expense belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.alter_column('expenses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this employee belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.alter_column('employees', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Primary key - explicitly named as pk_companies_id',
               existing_nullable=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this asset belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###

