"""add_slug_to_companies

Revision ID: c10ec52fad4f
Revises: 55c626fc25c6
Create Date: 2025-12-07 19:48:04.731788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10ec52fad4f'
down_revision: Union[str, None] = '55c626fc25c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.add_column('companies', sa.Column('slug', sa.String(length=50), nullable=False, comment='URL-friendly identifier (e.g. test-corp)'))
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.alter_column('expenses', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_comment='User role (admin, hr, employee) - indexed for fast role-based access control queries',
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (workspace) this record belongs to',
               existing_comment='Company (tenant) this record belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('ix_company_email', 'users', ['company_id', 'email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_email', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_comment='User role (admin, hr, employee) - indexed for fast role-based access control queries',
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
    op.alter_column('expenses', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_column('companies', 'slug')
    op.alter_column('assets', 'company_id',
               existing_type=sa.UUID(),
               comment='Company (tenant) this record belongs to',
               existing_comment='Company (workspace) this record belongs to',
               existing_nullable=False)
    # ### end Alembic commands ###

