"""Add expenses table for reimbursement management

Revision ID: c6249ba0db35
Revises: de3e89e4c06c
Create Date: 2025-11-03 22:07:28.006658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6249ba0db35'
down_revision: Union[str, None] = 'de3e89e4c06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Company (tenant) this expense belongs to'),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Employee who submitted this expense'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Expense title/description'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Expense amount (e.g., 125.50)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the expense'),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False, comment='Date when the expense was incurred'),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False, comment='Current status of the expense reimbursement'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='URL/path to uploaded receipt file (optional)'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User (HR/Admin) who approved/rejected this expense'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Date when expense was approved/rejected'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Reason for rejection (if status is rejected)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'reimbursed')", name='ck_expenses_status'),
    sa.CheckConstraint('amount >= 0', name='ck_expenses_amount_non_negative'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='fk_expenses_approved_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_expenses_company', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_expenses_employee', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_title'), 'expenses', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_title'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###

