"""Add assets table for device management

Revision ID: de3e89e4c06c
Revises: 7f94cd137cb9
Create Date: 2025-11-03 21:44:13.246110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3e89e4c06c'
down_revision: Union[str, None] = '7f94cd137cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Company (tenant) this asset belongs to'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Asset/item name (e.g., 'MacBook Pro 16')"),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='Type of asset (laptop, monitor, etc.)'),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='Serial number - unique within company'),
    sa.Column('status', sa.String(length=50), server_default='available', nullable=False, comment='Current status of the asset'),
    sa.Column('condition', sa.String(length=50), server_default='excellent', nullable=False, comment='Physical condition of the asset'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='Employee currently assigned this asset. NULL if unassigned.'),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True, comment='Date when asset was issued/assigned to current employee'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition IN ('excellent', 'good', 'fair', 'poor')", name='ck_assets_condition'),
    sa.CheckConstraint("status IN ('available', 'assigned', 'maintenance', 'retired')", name='ck_assets_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], name='fk_assets_employee', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_assets_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'serial_number', name='uq_assets_company_serial')
    )
    op.create_index(op.f('ix_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_assets_company_id'), 'assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_company_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_assigned_to'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###

